### ISSUE TITLE
毕业狗有时间来添加下，（甚至可以加上计科的专业课

### ISSUE THREAD

**Issue by JiaoMaWHU** [samar1tan/awesome-whu-public-elective#1]

**Comment by JiaoMaWHU** [comment]
当评论用了。。。看到了就close吧

**Comment by samar1tan** [comment]
谢谢，才看到2333。这repo是考试月创建的。本想着考完认真思考一下有没有必要弄和怎么弄，和淘课啦有何区别之类的，但鸽到现在（逃

**Comment by JiaoMaWHU** [comment]
淘课啦上面应该只有建议吧，北大，浙大好像都有这样的repo，里面有往届的各种复习资料。现在复习资料的传承应该都是靠学习部吧，没法调用很多人参与。

**Comment by JiaoMaWHU** [comment]
以前学长们的课设作业也可以贡献出来，帮助大家少走弯路，但是不知道会不会帮倒忙。。。

**Comment by samar1tan** [comment]
之前看到过一个项目[OpenWHU](https://github.com/openwhu/OpenWHU)是效仿北大、浙大等收集课设作业、复习资料等课程材料的。我这个repo是真的想帮大家选一些**给分好的公选课**（今年踩雷《音乐欣赏》，77.......

**Comment by samar1tan** [comment]
淘课啦有公选课平均给分、上过的人评价之类的，但是我觉得统计指标不够（比如没有考虑到选课同学的专业背景），也没有上课经验（比如怎么组队、怎么应对考勤之类的）、选课经验（哪些学院的课一般比较坑）这些。我感觉目前经验要不就口口相授，要不就淹没在学生会权益部门、学习部门的众多推文里，潜规则的属性强一点。就比如那门《音乐欣赏》均分也有85+但是今年就神坑，很多人80左右。貌似是因为学校公选课改革，给分变严了。

**Comment by samar1tan** [comment]
这个repo越说越像是经验分享，开个博文系列感觉就够了。和自强的知名度和数据量和应该是没法儿比。所以我也不太清楚怎么弄...

**Comment by JiaoMaWHU** [comment]
我竟然不知道还有OpenWHU..... 你说的有道理，看你自己咋想了

**Comment by JiaoMaWHU** [comment]
打不过就加入他们👀
